services:
 security-dashboard:
   build:
     context: .       # wichtig: das ist der docker/ Ordner
     dockerfile: Dockerfile
   image: retro-hunter
   container_name: retro-hunter-yamt
   ports:
     - "8501:8501"
   volumes:
     - ../file_index.db:/app/file_index.db
     - ../badfiles.db:/app/badfiles.db
     - ./certs:/app/certs
   restart: unless-stopped
